### ISSUE TITLE
Make Flying based on wrist position instead of head

### ISSUE THREAD

**Issue by RedBrumbler** [SideQuestVR/LegendsSDK#19]

**Comment by shaneharris** [comment]
ok make fly go straight up and down and not forward a bit

**Comment by Bald-Man-Gamer** [comment]
Or have flying only based on left and right head movement or totally independent from anything.

**Comment by shaneharris** [comment]
ok made the flying just go straight up and down regardless of head/hand orientation. Also added an option to enabled "Hand Based Movement" as a user configurable so forward/back movement and left/right can be based on the right hand orientation rather than the head. 

releasing today in the latest version.
